(function ($) {
/**
* @file
* Javascript, modifications of DOM.
*
* Manipulates links to include jquery load funciton
*/

Drupal.behaviors.ulima = {
  attach: function (context, settings) {
  // Capture barrio-modal class generated by Skinr.
  // This triggers block as modal.


  $( '<div class="block-content modal-body"></div>' ).insertAfter( ".modal-header" );
  $("#webform-client-form-15").appendTo(".block-content.modal-body");

// Load WOW.js on non-touch devices
var isPhoneDevice = "ontouchstart" in document.documentElement;
jQuery(document).ready(function() {
    if (isPhoneDevice) {
        //mobile
    } else {
        //desktop               
        // Initialize WOW.js
        wow = new WOW({
            offset: 50
        })
        wow.init();
    }
});



$('span.hamb').click(function (e) {
  $('body').toggleClass('secondary-active');
  $('.hamb').toggleClass('active');
  e.stopPropagation();
  e.preventDefault();
});




/* sticky */
$(document).ready(function() {sticker();});
$(document).scroll(function() {sticker();});

function sticker() {
var header =  jQuery('body');
var distancia_limit_1 = 100;
var distancia_limit_2 = 200;
var distancia_limit_3 = 600;
  
if (!jQuery('.ltie9').length) {
var distancia_scroll = jQuery(document).scrollTop();
} else {
var distancia_scroll = jQuery('html, body').scrollTop();
}
  
if ( distancia_scroll > distancia_limit_1 ) {
header.addClass('sticker-1');
} else {
header.removeClass('sticker-1'); 
}
if ( distancia_scroll > distancia_limit_2 ) {
header.addClass('sticker-2');
} else {
header.removeClass('sticker-2'); 
}
if ( distancia_scroll > distancia_limit_3 ) {
header.addClass('sticker-3');
} else {
header.removeClass('sticker-3'); 
}
};


    
  }

}

}(jQuery));




