(function ($) {
/**
* @file
* Javascript, modifications of DOM.
*
* Manipulates links to include jquery load funciton
*/

Drupal.behaviors.ulima = {
  attach: function (context, settings) {
  // Capture barrio-modal class generated by Skinr.
  // This triggers block as modal.


$('.modal-content ').append('<div class="modal-body"></div>');
$("#webform-client-form-15").appendTo(".modal-body");






/* sticky */
$(document).ready(function() {sticker();});
$(document).scroll(function() {sticker();});

function sticker() {
var header =  jQuery('body');
var distancia_limit_1 = 100;
var distancia_limit_2 = 200;
var distancia_limit_3 = 600;
  
if (!jQuery('.ltie9').length) {
var distancia_scroll = jQuery(document).scrollTop();
} else {
var distancia_scroll = jQuery('html, body').scrollTop();
}
  
if ( distancia_scroll > distancia_limit_1 ) {
header.addClass('sticker-1');
} else {
header.removeClass('sticker-1'); 
}
if ( distancia_scroll > distancia_limit_2 ) {
header.addClass('sticker-2');
} else {
header.removeClass('sticker-2'); 
}
if ( distancia_scroll > distancia_limit_3 ) {
header.addClass('sticker-3');
} else {
header.removeClass('sticker-3'); 
}
};


    
  }

}

}(jQuery));




