(function ($) {
/**
* @file
* Javascript, modifications of DOM.
*
* Manipulates links to include jquery load funciton
*/

Drupal.behaviors.edux = {
  attach: function (context, settings) {
  // Capture barrio-modal class generated by Skinr.
  // This triggers block as modal.
   alert("ffksnfsfd");
  jQuery('.modal').appendTo("body");
    
  }

}

}(jQuery));
