<?php



 
function simulador_menu() {
 

 $items['colegios_autocomplete'] = array(
   
    'page callback' => '_autocomplete',
    'access arguments' =>array('access content'),
    'type' => MENU_CALLBACK,
  );  


 $items['info_colegio'] = array(
   
    'page callback' => 'trae_data_colegio',
    'access arguments' =>array('access content'),
    'type' => MENU_CALLBACK,
  );  

 $items['info_colegios'] = array(
   
    'page callback' => 'trae_data_colegios',
    'access arguments' =>array('access content'),
    'type' => MENU_CALLBACK,
  ); 

  return $items;
}


/**
 * Implements hook_block_info().
 */
function simulador_block_info() {
  $blocks = array();
  $blocks['simulador'] = array(
    'info' => t('Simulador step'),
  );


  return $blocks;
}



function simulador_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'simulador':
      $block['subject'] = '';
      $block['content'] = get_data_html_modal();
      break;


  }
  return $block;
}


function _autocomplete($string = '') {
  //$string = $_POST["data"];
  $string = $_GET['term'];
  $matches = array();
  if ($string) {
    $result =  db_select('node', 'n')
  ->fields('n', array('nid', 'title'))
  ->condition('n.title', '%' . db_like($string) . '%', 'LIKE')
  ->condition('n.type', 'colegio')
  ->range(0, 10)
  ->execute()
  ->fetchAll();
    foreach ($result as $node) {
      //$matches[$node->nid] = check_plain($node->title);
       $matches[$node->nid]['value'] = check_plain($node->title);
       $matches[$node->nid]['key'] = $node->nid;
    }
  }

echo drupal_json_output($matches);

exit();
}


function trae_data_colegio($string = '') {

  $string = $_POST["nid"];
  //$string = $_GET['term'];
 $nid = (int)$string;
  $nodo = node_load($nid);

 $tid = $nodo->field_categor_a_de_pago['und'][0]['tid'];
 $termino = taxonomy_term_load($tid);
 $terminoglobal = taxonomy_term_load(22);  
 $mes =  date("n", strtotime("now"));

     $respuesta = new stdClass();
    //$respuesta->nombre = "cristhian";
   // $respuesta->paterno = "sanchez";
    $respuesta->tipocolegio =  $nodo->field_tipo['und'][0]['value'];
    $respuesta->categoria = $termino->name;
    $respuesta->valorcredito = $termino->field_valor_credito_term['und'][0]['value'];
    $respuesta->derechomatricula = $terminoglobal->field_valor['und'][0]['value'];
    $respuesta->periodos = get_data_periodos($mes);
echo drupal_json_output($respuesta);

exit();
}


function trae_data_colegios() {
$news_items_nids = array();
$categorias = array();
  $news_items_nids[] = $_POST['nid1'];
  $news_items_nids[] =$_POST['nid2'];
  $news_items_nids[] = $_POST['nid3'];
  //$string = $_GET['term'];


  
 
 $news_items = entity_load('node', $news_items_nids);

  foreach ($news_items as $key => $value) {
    $tid = $value->field_categor_a_de_pago['und'][0]['tid'];
    $categorias[$value->nid]=  taxonomy_term_load($tid)->name;
    
   
  }

$nid = get_nid($categorias);


  $nodo = node_load($nid);

 $tid = $nodo->field_categor_a_de_pago['und'][0]['tid'];
 $termino = taxonomy_term_load($tid);
 $terminoglobal = taxonomy_term_load(22);  
 $mes =  date("n", strtotime("now"));

     $respuesta = new stdClass();
    //$respuesta->nombre = "cristhian";
   // $respuesta->paterno = "sanchez";
    $respuesta->nid =  $nid;
    $respuesta->categoria = $termino->name;
    $respuesta->valorcredito = $termino->field_valor_credito_term['und'][0]['value'];
    $respuesta->derechomatricula = $terminoglobal->field_valor['und'][0]['value'];
    $respuesta->periodos = get_data_periodos($mes);
echo drupal_json_output($respuesta);

exit();
}
function get_nid($categorias){
$pe = null;
$qu = null;
$er = null;
$ese = null;
$te = null;

    $pe = array_search('P', $categorias);
    if($pe !== false ) {
      return $pe;
    }
    $qu = array_search('Q', $categorias);
    if($qu !== false ) {
      return $qu;
    }
     $er = array_search('R', $categorias);
    if($er !== false ) {
      return $er;
    }

       $ese = array_search('S', $categorias);
    if($ese !== false ) {
      return $ese;
    }
     

       $te = array_search('T', $categorias);
    if($te !== false ) {
      return $te;
    }
    
    

  
  
}

function get_data_periodos($mes){
$periodos = array();
$tid = 0;

switch ($mes) {


  case 1:
  case 2:
  case 3:
  case 4:
  case 5:
  case 6:
      $tid = 23;
    
    break;
  
  case 6:
  case 7:
  case 8:
  case 9:
  case 10:
  case 11:
  case 12:
    $tid = 24;
  break;
}

$terminoperido =taxonomy_term_load($tid);

$fechasperiodos = $terminoperido->field_fechas_simulador['und'];
foreach ($fechasperiodos   as $key => $value) {
  $periodos[$key]['inicio'] = date("d.m.y",$value['value']);
  $periodos[$key]['final'] = date("d.m.y",$value['value2']);
}


return $periodos;

}

function get_data_html_modal() {


drupal_add_js(drupal_get_path('module', 'simulador') . '/modal-steps.min.js');
drupal_add_js(drupal_get_path('module', 'simulador') . '/simulador.js');
drupal_add_css(drupal_get_path('module', 'simulador') . '/simulador.css',array('group' => CSS_DEFAULT, 'every_page' => TRUE));


//$modal1 ='<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal1">Launch demo modal </button>'; el boton ya esta colocado
$modal1 = '<div class="modal fade simulador" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close closer" data-dismiss="modal" aria-label="Close">X</button>
        
      </div>
      <div class="modal-body">';
   $modal1 .= '<div class="menu" >
    

         <div class="calculadora">
              <ul>
                <li>Inversión &gt;  </li>
                    <li>Simulador de pensiones &gt;  </li>
                     <li>Elige tus colegios  </li>
              </ul>
              <div class="cont_calculadora cal1">
                    <h2>¿Cuál es tu caso?</h2>
                        <div class="cont_casos_cal">
                          <div class="casoCole ">
                            <a class="uncolegio">
                              <figure>
                                  <img src="/sites/all/themes/ulima/img/colegio1.jpg">
                                </figure>
                                <h4>
                                  Estudié de tercero a quinto año de secundaria 
                                    <strong>en un mismo colegio</strong>
                                </h4>
                            </a>
                                     
                            
                            </div>
                            <div class="casoCole cole2 ">
                            <a class="varioscolegio">
                              <figure>
                                  <img src="/sites/all/themes/ulima/img/colegio2.jpg">
                                </figure>
                                <h4>
                                  Estudié de tercero a quinto año de secundaria 
                                    <strong>en un mismo colegio</strong>
                                </h4>
                            </a>                      
                                                        
                            </div>                       
                        </div>
                         
                       
                        <h3>
                           La información que obtenga este simulador es referencial. Su categoria de pago será asignada al momento de su inscripción al concurso de admisión.
                        </h3>
              </div>
            </div>
     
    </div>';
 $modal1 .='</div> </div> </div></div>';

//$modal ='<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Launch demo modal </button>';
$modal ='';
$modal .= '<div class="modal fade simulador " id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close closer cerrar" data-dismiss="modal" aria-label="Close">X</button>
       
      </div>
      <div class="modal-body">';



$modal .= '<div class="row hide" data-step="1">

            <div class="calculadora step">
          <ul>
            <li>Inversión &gt;  </li>
                <li>Simulador de pensiones &gt;  </li>
                <li>Elige tu colegio  </li>
          </ul>
          <div class="cont_calculadora">
                <h2>Elige tu colegio</h2>
                    
                    <div class="select_cal">
                       
                      <div class="ui-widget">
                        <input type="text" id="search-box" class="form-control autocomplete ui-autocomplete-input" placeholder="Selecciona tu colegio" />
                        <label id="selectID"></label>
                        <label id="nombre"></label>
                      </div>
                    </div>
                    
                     
                    <h3>
                      Los nombres de los colegios serán verificados por la Universidad de Lima al momento de su inscripción al concurso de admisión
                    </h3>
                    
                    <div class="cont_botones_cal">
                    <div class="modal-footer">
                      <div class="cont_conmas">


      
    
      

                            <div class="smas">
                                <span><a href="" tabindex="0">Volver </a>
                                </span>
                            </div>
                            <div class="smas smas2">
                                <span><a class="btn btn-success scroller js-btn-step" data-orientation="next" ></a></span>
                            </div>

                  

                      </div>
                        </div>
                    </div>
            </div>
        </div>


        </div>';



 $modal .='<div class="row hide " data-step="2">

      <div class="calculadora step">
        <ul>
            <li>Inversión &gt;  </li>
                <li>Simulador de pensiones    </li>
               
          </ul>
        <div class="cont_calculadora">
                <h2>Tu categoria es</h2>
                      <div class="cont_categoria">
                          <div class="cat1">
                              <h3>CATEGORIA</h3>
                              <h2 id="categoria"></h2>
                            </div>
                          <div class="cat2">
                              <h3>VALOR DEL CREDITO</h3>
                              <h2 ><span>S/</span><span id="valorcredito"></span><span>.00*</span></h2>
                            </div>
                        </div>
                        <h4 class="mens">*En función de la información brindada por usted</h4>
                    
                      <div class="cont_creditos">
                        <h3>Elige tu cantidad de créditos*</h3>
                          <div class="num_credit">
                              <span class="menos">-</span>
                              <span class="num"> 20 </span>
                              <span class="mas">+</span> 
                            </div> 
                        </div> 
                    <h3>
                     *Solo en el primer ciclo, el ingresante debe matricularse en el total de creditos correspondientes al primer nivel de plan de estudios. Apartir del segundo ciclo, el alumno puede matricularse en la cantidad de créditos que elija.
                    </h3>
                    <div class="n_tasas">
                      <div class="item_tasa">
                          <span>
                              Derecho de enseñanza [<label class="num2"> 20 </label> créditos]
                            </span>
                            <h4 ><span>S/</span><span id="derechoense"></span><span>.00</span></h4>
                        </div>
                        <div class="item_tasa">
                          <span>
                              Derecho de matrícula
                            </span>
                            <h4 ><span>S/</span><span id="derechomatricula"></span><span>.00</span></h4>
                        </div>
                       
                         <div class="item_tasa t_total">
                          <span>
                            Total ciclo
                            </span>
                            <h4 ><span>S/</span><span id="totalciclo"></span><span>.00</span></h4>
                        </div>
                    
                    </div>
                    
                    
                    <div class="modal-footer">
                      <div class="cont_conmas">
                            <div class="smas">
                              <span><a class="btn btn-success nonscroller js-btn-step" data-orientation="previous" ></a></span>
                            </div>
                            <div class="smas">
                                <span><a href="javascript:window.print()" tabindex="0">Imprimir </a>            </span>

                            </div>
                            <div class="smas smas2">
                              <span><a class="btn btn-success nonscroller js-btn-step" data-orientation="next" ></a></span>
                            </div>
                        </div>
                    </div>
            </div>

        </div>
  </div>';




 $modal .='<div class="row hide" data-step="3" data-title="This is the last step!">
            <div class="cont_login s_cuotas">
                    <h2>Simulador de cuotas</h2>
   
                   <div id="reportesimu"></div>
                <div class="modal-footer">
                    <div class="cont_conmas">
                            <div class="smas">
                                <span><a class="btn btn-success cerrar js-btn-step" data-orientation="cancel" ></a></span>
                            </div>
                            <div class="smas smas2">
                                <span><a href="javascript:window.print()" tabindex="0">Imprimir </a>            </span>
                            </div>
                    </div>
                </div>        
            </div>
  </div>

</div>
  
    </div>
  </div>
</div>';

$modal .= '<script>jQuery("#myModal").modalSteps();</script>';





/*varios colegios*/
//$modal ='<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">Launch demo modal </button>';
$modal2 ='';
$modal2 .= '<div class="modal fade simulador " id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close closer cerrar" data-dismiss="modal" aria-label="Close">X</button>
       
      </div>
      <div class="modal-body">';



$modal2 .= '<div class="row hide" data-step="1">

            <div class="calculadora step">
          <ul>
            <li>Inversión &gt;  </li>
                <li>Simulador de pensiones &gt;  </li>
                <li>Elige tus colegios  </li>
          </ul>
          <div class="cont_calculadora">
                <h2>Elige tu colegio</h2>
                    
                    <div class="select_cal">
                       
                      <div class="ui-widget">
                       <span class="labelanio">Tercer año</span> <input type="text" id="search-box-1" class="form-control autocomplete ui-autocomplete-input colegiosauto" placeholder="Selecciona tu colegio" />
                        <label id="selectID-1"></label>
                        
                        <span class="labelanio">Cuarto año</span><input type="text" id="search-box-2" class="form-control autocomplete ui-autocomplete-input colegiosauto" placeholder="Selecciona tu colegio" />
                        <label id="selectID-2"></label>

                        <span class="labelanio">Quinto año</span><input type="text" id="search-box-3" class="form-control autocomplete ui-autocomplete-input colegiosauto" placeholder="Selecciona tu colegio" />
                        <label id="selectID-3"></label>
                      </div>
                    </div>
                    
                     
                    <h3>
                      Los nombres de los colegios serán verificados por la Universidad de Lima al momento de su inscripción al concurso de admisión
                    </h3>
                    
                    <div class="cont_botones_cal">
                    <div class="modal-footer">
                      <div class="cont_conmas">


      
    
      

                            <div class="smas">
                                <span><a href="" tabindex="0">Volver </a>
                                </span>
                            </div>
                            <div class="smas smas2">
                                <span><a class="btn btn-success getdata scroller js-btn-step" data-orientation="next" ></a></span>
                            </div>

                  

                      </div>
                        </div>
                    </div>
            </div>
        </div>


        </div>';



 $modal2 .='<div class="row hide " data-step="2">

      <div class="calculadora step">
        <ul>
            <li>Inversión &gt;  </li>
                <li>Simulador de pensiones    </li>
               
          </ul>
        <div class="cont_calculadora">
                <h2>Tu categoria es</h2>
                      <div class="cont_categoria">
                          <div class="cat1">
                              <h3>CATEGORIA</h3>
                              <h2 id="categoria-1"></h2>
                            </div>
                          <div class="cat2">
                              <h3>VALOR DEL CREDITO</h3>
                              <h2 ><span>S/</span><span id="valorcredito-1"></span><span>.00*</span></h2>
                            </div>
                        </div>
                        <h4 class="mens">*En función de la información brindada por usted</h4>
                    
                      <div class="cont_creditos">
                        <h3>Elige tu cantidad de créditos*</h3>
                          <div class="num_credit">
                              <span class="menos-1">-</span>
                              <span class="num-1"> 20 </span>
                              <span class="mas-1">+</span> 
                            </div> 
                        </div> 
                    <h3>
                     *Solo en el primer ciclo, el ingresante debe matricularse en el total de creditos correspondientes al primer nivel de plan de estudios. Apartir del segundo ciclo, el alumno puede matricularse en la cantidad de créditos que elija.
                    </h3>
                    <div class="n_tasas">
                      <div class="item_tasa">
                          <span>
                              Derecho de enseñanza [<label class="num2-1"> 20 </label> créditos]
                            </span>
                            <h4 ><span>S/</span><span id="derechoense-1"></span><span>.00</span></h4>
                        </div>
                        <div class="item_tasa">
                          <span>
                              Derecho de matrícula
                            </span>
                            <h4 ><span>S/</span><span id="derechomatricula-1"></span><span>.00</span></h4>
                        </div>
                       
                         <div class="item_tasa t_total">
                          <span>
                            Total ciclo
                            </span>
                            <h4 ><span>S/</span><span id="totalciclo-1"></span><span>.00</span></h4>
                        </div>
                    
                    </div>
                    
                    
                    <div class="modal-footer">
                      <div class="cont_conmas">
                            <div class="smas">
                              <span><a class="btn btn-success nonscroller js-btn-step" data-orientation="previous" ></a></span>
                            </div>
                            <div class="smas">
                                <span><a href="javascript:window.print()" tabindex="0">Imprimir </a>            </span>

                            </div>
                            <div class="smas smas2">
                              <span><a class="btn btn-success nonscroller js-btn-step" data-orientation="next" ></a></span>
                            </div>
                        </div>
                    </div>
            </div>

        </div>
  </div>';




 $modal2 .='<div class="row hide" data-step="3" data-title="This is the last step!">
            <div class="cont_login s_cuotas">
                    <h2>Simulador de cuotas</h2>
   
                   <div id="reportesimu-1"></div>
                <div class="modal-footer">
                    <div class="cont_conmas">
                            <div class="smas">
                                <span><a class="btn btn-success cerrar js-btn-step" data-orientation="cancel" ></a></span>
                            </div>
                            <div class="smas smas2">
                                <span><a href="javascript:window.print()" tabindex="0">Imprimir </a>            </span>
                            </div>
                    </div>
                </div>        
            </div>
  </div>

</div>
  
    </div>
  </div>
</div>';

$modal2 .= '<script>jQuery("#myModal2").modalSteps();</script>';




/* end varios coelgios*/


 return $modal2.$modal.$modal1 ;

}









