<?php

/**
 * @file
 * Contains module for the bxslider block.
 */

/**
 * Bx slider module.
 */
use Drupal\bxslider_block\BXSliderModel;

/**
 * Implements hook_theme().
 */
function bxslider_block_theme($existing, $type, $theme, $path) {
  $theme = [];

  // Frontend.
  $theme['bx_slider'] = [
    'variables' => [
      'slider_name' => NULL,
      'bxid' => NULL,
      'machine_name' => NULL,
      'items' => [],
      'settings' => NULL,
    ],
    'path' => $path . '/templates',
  ];

  return $theme;
}

/**
 * Implements hook_libraries_info_alter().
 */
function bxslider_block_libraries_info_alter(&$libraries) {
  $debug = 1;

}

/**
 * Implements hook_library_info_alter().
 */
function bxslider_block_library_info_alter(&$libraries, $extension) {


}
