(function ($) {
/**
* @file
* Javascript, modifications of DOM.
*
* Manipulates links to include jquery load funciton
*/

Drupal.behaviors.ulima = {
  attach: function (context, settings) {
  // Capture barrio-modal class generated by Skinr.
  // This triggers block as modal.

$(document).ready(function() {



    //jQuery("#slick-views-carrusel-carreras-14").prepend('<span class="left-arrow slick-prev slick-arrow" style="display: block;"><img src="/sites/all/themes/ulima/img/svg/arrow_r.svg"></span>');

      $(".hmb").click(function(event) {
          event.preventDefault();
        $(".nav.menudo").toggleClass("menu_on");
        });
     

     $('#block-views-carrusel-carreras-block-1 .left-arrow.slick-prev.slick-arrow').each(function(){
      $(this).insertBefore($(this).parent());
    });

      $('#block-views-carrusel-carreras-block-1 .right-arrow.slick-next.slick-arrow').each(function(){
      $(this).insertBefore($(this).parent());
    });

     $( ".menu_nav ul li" ).prepend( "<span></span>" );
     $( ".cont_fechas" ).prepend('<span class="circle"></span>');

     $( ".left-arrow.slick-arrow" ).prepend('<img src="/sites/all/themes/ulima/img/svg/arrow_l.svg">');
     $( ".right-arrow.slick-arrow" ).prepend('<img src="/sites/all/themes/ulima/img/svg/arrow_r.svg">');

     $(".webform-component--cerrar").appendTo(".modal-dialog");
     $('.close').on('click', function(){ 

      $('#block-webform-client-block-15').modal('hide');
      

      });

     $( "ul.fila li" ).prepend( "<i></i>" );

    $("#play-video").on('click', function(ev) { 
      $('.videosss').css('display','block');
      $('.cont_vi_emple').css('display','none');

       $("#youtube-field-player")[0].src += "&autoplay=1";
       
       
    ev.preventDefault();
 
   
 
  });


    $('.select_pais select').change(function () {
         var tid = $(this).val();
      $.ajax({
        type: 'POST',
        url: 'info_pais',
        data: {
            'tid': tid
        },
        success: function (data) {
            

            var sede = data.sede;
            var imagen = data.imagen;
          $(".mod_univ h2").text(sede);
          $(".fac figure img").attr("src", imagen);
           console.log(data);
           var convenios = data.convenios;
           var tmpl = "";
           for (var i = 0; i < convenios.length; i++) {
            tmpl += "<li><a href='" + convenios[i]['url'] + "'>" + convenios[i]['universidad'] + "</a></li>";
          }
          $(".mod_univ ul").empty();
          $(".mod_univ ul").append(tmpl);
            
        }
    });

    });

jQuery('#slick-views-carrusel-videos-infraestrcutura-2 a').attr('data-fancybox', 'comunicacion');
jQuery('#slick-views-carrusel-videos-infraestrcutura-3 a').attr('data-fancybox', 'derecho');
jQuery('#slick-views-carrusel-videos-infraestrcutura-4 a').attr('data-fancybox', 'psicologia');  
jQuery('#slick-views-carrusel-videos-infraestrcutura-5 a').attr('data-fancybox', 'economia');
jQuery('#slick-views-carrusel-videos-infraestrcutura-6 a').attr('data-fancybox', 'ingenieria');

$('#quicktabs-galerias_imagenes_videos_por_fac ul li a').on('click', function(){ 

  jQuery('#slick-views-carrusel-videos-infraestrcutura-2 a').attr('data-fancybox', 'comunicacion');
jQuery('#slick-views-carrusel-videos-infraestrcutura-3 a').attr('data-fancybox', 'derecho');
jQuery('#slick-views-carrusel-videos-infraestrcutura-4 a').attr('data-fancybox', 'psicologia');  
jQuery('#slick-views-carrusel-videos-infraestrcutura-5 a').attr('data-fancybox', 'economia');
jQuery('#slick-views-carrusel-videos-infraestrcutura-6 a').attr('data-fancybox', 'ingenieria');

$('.slick-arrow').trigger("click");

});


$('#block-views-carrusel-carreras-block-1 .slick__slide.slide.slide--0.slick-slide').addClass('crisito');
$('#block-views-carrusel-carreras-block-1 span.li a').on('click', function(){ 

$('#block-views-carrusel-carreras-block-1 .view-content .slick__slide').removeClass('crisito');
$(this).parent().parent().parent().addClass("crisito");
$('.tererererere .slick-arrow').trigger("click");
$('.paragraphs-item-infraestructura-talleres-laborat').trigger("click");

});


$('.uncolegio').on('click', function(){ 

$('#myModal1').modal('hide');
$('#myModal').modal();

});

$('.varioscolegio').on('click', function(){ 

$('#myModal1').modal('hide');
$('#myModal2').modal();

});

  


var url = window.location.href;
if(url.indexOf('?field_tipo_value=') > 0){
  
    $('.view-buscador-colegio .c_ingresar').css("display","block");
}});

jQuery('.modal').appendTo("body");

  $( '<div class="block-content modal-body"></div>' ).insertAfter( ".modal-header" );
  $("#webform-client-form-15").appendTo(".block-content.modal-body");


          var selector = '.cont_olima .carreras  li';

            $(selector).on('click', function(){
                  if (jQuery(this).hasClass('active')) {
                   $(this).removeClass('active');
                  }
                  else {
                   $(this).addClass('active');
                }
          
        });
  

  $('#webform-client-form-15 button').on('click', function(){
  var count = $('#edit-submitted-charlas').val().length;


   var valuesdates = $('#edit-submitted-date').val();
   var resdates = valuesdates.split("|"); 
   
   var text = "";
   var i;
   var valor = 0;
  if(count===0) {
    
    $('.mensajeerror').text("Debe escoger al menos una charla");
    return false;
  }
  else {
         for (i = 0; i < resdates.length; i++) {
          var newi = resdates.length - (i + 1) ;
          var p;

          for (p = 1; p <= newi; p++) {

          text += resdates[i] + '-'+resdates[i + p] + '<br/>';

          if(resdates[i] === resdates[i + p]) {
              valor = 1;
           

          } 
       }
      }

        if(valor == 1 ) {
            $('.mensajeerror').text("Por favor verificar, no puedes inscribirte a más de una charla a la misma hora en el mismo día");
             return false;
           }else {

            return true;
           }

  }

  

});


    $('#btn-block-webform-client-block-15 button').on('click', function(){

       var tab_attribs = [];
        var dates = [];
       $('.carreras ul li.active').each(function () {
       tab_attribs.push( jQuery(this).attr("data-id") );
        dates.push(jQuery(this).attr("data-date"));
         });
     var stte = tab_attribs.join("|");
     var fechas = dates.join("|");
     $('#edit-submitted-charlas').val(stte);
     $('#edit-submitted-date').val(fechas);
   
});





    

    jQuery("input[name='field_tipo_value']:checked").parent().addClass("active"); 
    $('#edit-field-tipo-value-wrapper .form-item-field-tipo-value label').on('click', function(){
          
              $('#edit-field-tipo-value-wrapper .form-item-field-tipo-value label').removeClass('active');
                 
                   $(this).addClass('active');
                
      });

    //$('#edit-field-tipo-value-wrapper .form-item-field-tipo-value:nth-child(2) label').addClass('active');
    //$('#edit-field-tipo-value-particular').attr('checked', true);
    $("#edit-field-tipo-value-wrapper input:radio:checked").next('label').addClass("checked");
     $('.buscador-colegio input#edit-title').attr("placeholder", "Escribe el nombre de tu colegio");

    $('.buscador-colegio .view-content').addClass("c_ingresar");
    $('.page-node-73 #block-system-main').addClass("col-md-6 col-lg-6");

// Load WOW.js on non-touch devices
var isPhoneDevice = "ontouchstart" in document.documentElement;
jQuery(document).ready(function() {
    if (isPhoneDevice) {
        //mobile
    } else {
        //desktop               
        // Initialize WOW.js
        wow = new WOW({
            offset: 50
        })
        wow.init();
    }
});



$('span.hamb').click(function (e) {
  $('body').toggleClass('secondary-active');
  $('.hamb').toggleClass('active');
  e.stopPropagation();
  e.preventDefault();
});







    
  }

}

}(jQuery));




