<?php

/**
 * @file
 * Contains contacto.module
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */

function contacto_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the multi_step module.
        case 'help.page.contacto':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Multi Step Form') . '</p>';
            return $output;
            break;
    }
}

/**
 * Implements hook_theme().
 */

function contacto_theme($existing, $type, $theme, $path) {

    return [
        'contacto' => [
            'render element' => 'form',
        ],

    ];
}

function openulima_theme($existing, $type, $theme, $path) {
    return [
        'openulima' => [
            'render element' => 'form',
        ],

    ];
}